---
title: Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
  uploads:
    title: Uploads
    output: true
name: Rita G Furlong
brand: Rita G Furlong
description: Rita G Furlong
keyword:
url: https://ritagfurlong.github.io/site/
email: ritagfurlong1@gmail.com
twitter:
github:
author: Rita G Furlong
year:
markdown: kramdown
exclude:
- node_modules
